### ISSUE TITLE
I cant sleep

### ISSUE THREAD

**Issue by deleolajide** [deleolajide/binaries#1]
### Contact Details

dele@4ng.net

### What happened?

I cant sleep anymore

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
aaaaa
bbbbbbbbb
```
https://github.com/deleolajide/binaries/blob/main/docs/_config.yml

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olajidedele** [comment]
ok
